### ISSUE TITLE
Normalize

### ISSUE THREAD

**Issue by NanWangAC** [anheidelonghu/ACNet#13]
how the normalization map to the two datasets? Is there lost a depth normalization?
```
# image = torchvision.transforms.Normalize(mean=[0.485, 0.456, 0.406],
        #                                          std=[0.229, 0.224, 0.225])(image)
        image = torchvision.transforms.Normalize(mean=[0.4850042694973687, 0.41627756261047333, 0.3981809741523051],
                                                 std=[0.26415541082494515, 0.2728415392982039, 0.2831175140191598])(image)
        depth = torchvision.transforms.Normalize(mean=[2.8424503515351494],
                                                 std=[0.9932836506164299])(depth)
```

**Comment by anheidelonghu** [comment]
Each dataset has it's own normalization parameters. 
Depth is also normalized accroding to the code.

**Comment by NanWangAC** [comment]
i know, but there are two rgb normalization and one normaliztion in your code, so i want to know the relationship between them and nyudv2/SUN datasets.

**Comment by anheidelonghu** [comment]
Hi,


NYUDv2 and SUNRGBD have different normalization parameters which can be calculated by several methods, choose what performs better.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"WN"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月17日(星期二) 下午3:42
收件人:&nbsp;"anheidelonghu/ACNet"<ACNet@noreply.github.com&gt;;
抄送:&nbsp;"1207186994"<1207186994@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [anheidelonghu/ACNet] Normalize (#13)




i know, but there are two rgb normalization and one normaliztion in your code, so i want to know the relationship between them and nyudv2/SUN datasets.
