### ISSUE TITLE
Could you send me the code of the SUN RGB-D? My email is 3166808160@qq.com

### ISSUE THREAD

**Issue by zhouqi946** [anheidelonghu/ACNet#17]

**Comment by anheidelonghu** [comment]
The code for NYUDv2 and SUN-RGBD is the same, just modify [ACNet_data_nyuv2.py](https://github.com/anheidelonghu/ACNet/blob/master/ACNet_data_nyuv2.py) to load SUN-RGBD dataset, and then you can get the training result.
