### ISSUE TITLE
Two questions about the visualization of your paper

### ISSUE THREAD

**Issue by TXH-mercury** [anheidelonghu/ACNet#18]
Hi @anheidelonghu 
I have two questions about the feature visualization part of your paper,looking forward your reply!
The First : Layer 2 have 512 channels while the paper says 128channels
The Second :  single-channel visualization should be gray image ,how do you convert it to the color image as the paper show? Thank you 
![image](https://user-images.githubusercontent.com/38175683/91467232-e87c9680-e8c2-11ea-867d-1525bbb963fb.png)

![image](https://user-images.githubusercontent.com/38175683/91467267-efa3a480-e8c2-11ea-917b-0ad7c9e4c4fe.png)

**Comment by anheidelonghu** [comment]
Thank you for your attention!
1. You are right, I take mistake in channel numbers in paper.
2. the gray image can be converted to color map in many ways, you can use OpenCV to convert it. In this paper, blue represents low and red represents high.
