### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by hhhwww123** [anheidelonghu/ACNet#2]
首先，感谢您开源如此优秀的代码。但是我在运行你的代码的时候，出来的结果并没有您论文中的那么好，我怀疑是我在准备数据的时候的问题，想和您进一步沟通，但是没有找到您的联系方式，请问你的邮箱是多少呢？？

**Comment by hhhwww123** [comment]
hello，有人在吗？？？

**Comment by anheidelonghu** [comment]
你好，我的邮箱是hxx_zju@zju.edu.cn。
