### ISSUE TITLE
RuntimeError: cuda runtime error (700)

### ISSUE THREAD

**Issue by mxt123dx** [anheidelonghu/ACNet#20]
when we run the train.py , we found the problem :RuntimeError: cuda runtime error (700) : an illegal memory access was encountered at /opt/conda/conda-bld/pytorch_1570910687650/work/aten/src/THC/THCReduceAll.cuh:327. we hope that we can get someone help!
Thanks very much!

**Comment by SunXusheng5200** [comment]
i have the same problem with you.
have you solve it?

**Comment by anheidelonghu** [comment]
Maybe it is caused by PyTorch version, make sure your pytorch version is 0.4.1

**Comment by Jinczhg** [comment]
This error message alone is not providing any info but perhaps try lowering your batch size
