### ISSUE TITLE
problem about DataSet SUNRGBD

### ISSUE THREAD

**Issue by RaymondChanSZU666** [anheidelonghu/ACNet#22]
Did you repair the DataSet SUNRGBD when you trained in your network?
If you had repair, what methods did you use? Can you give me the Dataset you had repair?
My email is 765886113@qq.com
thanks so much

**Comment by anheidelonghu** [comment]
Transfering dataset to .npy is just for better load, it's unnecessary to repair the dataset when you use the model.
