### ISSUE TITLE
Thanks for the great work! I have tried to reproduce the reported results (48.3%), but my test mIOU is only 45.7%. I think the main reason for this may be the different pre-processing of the dataset. So could you please share your processed NYUv2 dataset? Thanks in advance :)

### ISSUE THREAD

**Issue by xiong-zhitong** [anheidelonghu/ACNet#4]

**Comment by anheidelonghu** [comment]
The dataset url you request is available at the readme.md now.

**Comment by xiong-zhitong** [comment]
Thanks for your reply!

**Comment by phoebe0920** [comment]
>Excuse me ,can you solve the problem and  share the dataset ? 
 l make the datasets according  to the readme.md, but my test accuracy is zero ,l think it is properly related with the dataset, I am looking forward to hearing from you，thank you!
