### ISSUE TITLE
Depth preparation

### ISSUE THREAD

**Issue by Crocs512** [anheidelonghu/ACNet#6]
Hi @anheidelonghu 

I have a little minor problem about the depth preparation when i eval your model .

Did you convert depth to jet colorspace?  If so，should i do this transform too when I reproduce your model? 

Looking forward to your reply. Thanks!!

**Comment by anheidelonghu** [comment]
I only convert depth to .npy format for convenience, You can use depth directly in your dataloader script.

**Comment by Crocs512** [comment]
Thanks!!!
