### ISSUE TITLE
Segmentation fault with tensorboardX

### ISSUE THREAD

**Issue by Sibyl233** [anheidelonghu/ACNet#8]
I met the problem as follows when I train the model:

> Segmentation fault(core dumped)

I guess it is caused by command of tensorboardX, so I ran the official demo.py of tensorboardX and met the same problem.
Would you like to tell me the version of tensorboardX and tensorboard?

**Comment by anheidelonghu** [comment]
You can try tensorboard==1.11.0 and tensorboardX==1.2

**Comment by kshpv** [comment]
Hello, @Sibyl233 !
I have the same issue. How did you solve it?
@anheidelonghu, I tried  tensorboard==1.11.0 and tensorboardX==1.2. It didn't help

**Comment by kshpv** [comment]
I solved it. The problem was that my device didn't have enough memory for training.
